name: dbt build & docs

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dbt (duckdb)
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-duckdb

      - name: Show versions
        run: dbt --version

      - name: Install deps
        run: dbt deps --profiles-dir .

      - name: Seed
        run: dbt seed --profiles-dir .

      - name: Build (models + tests)
        run: dbt build --profiles-dir .

      - name: Generate docs
        run: dbt docs generate --profiles-dir .

      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: dbt-docs
          path: target
